# Generated by Django 2.1.7 on 2019-02-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='Add Something'),
        ),
    ]
