# Generated by Django 2.1.7 on 2019-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
